### ISSUE TITLE
Support the import issues bulk import API for migrating from gitlab

### ISSUE THREAD

**Issue by mattip** [fastai/ghapi#121]
I wish to import a project from gitlab with over 3500 issues and many comments. When using the [node-github-2-gitlab](https://github.com/piceaTech/node-gitlab-2-github/issues/28), I was stymied by two problems:
- Every `@` reference in an issue or comment caused a notification to be sent to the user.
- The API is rate limited

When I asked on github support what they recommend, I was referred to [this gist](https://gist.github.com/jonmagic/5282384165e0f86ef105) which describes a import api endpoint `https://api.github.com/repos/${GITHUB_USERNAME}/${GITHUB_REPO}/import/issues` but I do not see it used here. Is this endpoint usable from ghapi?

**Comment by jph00** [comment]
I'm not familiar with it, but is it one of these? https://ghapi.fast.ai/fullapi.html#migrations

**Comment by mattip** [comment]
No, I did not see the import/issues endpoint in the full api documentation. Did you close this as "done, the endpoint is now in use" or as "sorry, cannot use that"?
