### ISSUE TITLE
NameError: name 'urlsend' is not defined

### ISSUE THREAD

**Issue by jlinnett-montai** [fastai/ghapi#142]
I'm getting `NameError: name 'urlsend' is not defined` when trying to call `api.pulls.list`. It seems to be the same problem addressed in #140, which was then reverted in #141 with the comment "@jph00 you are right this import was not needed. Sorry for the confusion." 

Would anyone be able to expand on this at all — what the problem is, what the solution is, and why the import is not needed?

![Screen Shot 2022-07-13 at 11 10 28 AM](https://user-images.githubusercontent.com/90263752/178769009-e147baea-9622-481d-834a-19f820607394.png)

**Comment by jph00** [comment]
Sure! fastcore.all already contains that symbol in the latest version of fastcore, so you don't need to import it. I've just now updated the requirements on ghapi to require that version of fastcore, so if you upgrade ghapi it should also get you the correct version of fastcore.
