### ISSUE TITLE
CLI Not Clear

### ISSUE THREAD

**Issue by elJoeyJojo** [fastai/ghapi#146]
So I thought this tool would be easier to use but turns out to be more complicated than gh cli itself. I read the documentation for _repos.list_for_org_ and it saids it takes in an org as the only **required** but then when I run it I keep getting 500 Errors.

If I run _gh repo list_ I get the repos list immediately so not really sure if this ghapi works as intended or not but literally nothing works. If I try _repos.get owner repo-name_ I again get 500

**Comment by jph00** [comment]
We can pass back what we get from the GitHub API sorry. Perhaps you're not authenticated?
