### ISSUE TITLE
Self documenting api object does not work as described in docs

### ISSUE THREAD

**Issue by TaylorEllington** [fastai/ghapi#160]
In the documentation there is a section that reads:

```
Every part of the API includes documentation directly in the api object itself. For instance, here’s how to explore the groups of functionality provided by the API by displaying the object:

> api
```

followed by a long bulleted list of api targets. however this code sample seems to be inaccurate. as running the code in interactive mode results in 

> \>\>\>api
> <class 'ghapi.core.GhApi'> 

This occurred on python 3.10, running on Windows

**Comment by jph00** [comment]
This functionality requires Jupyter Notebook.
