### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by bmunkholm** [fastai/ghapi#161]
@jph00 As I'm trying to choose an SDK for Github I wonder if this is still being maintained as I can see it's been a while since the last release.

**Comment by jph00** [comment]
Yup still maintained. We do a release any time it's needed!

**Comment by bmunkholm** [comment]
You wouldn't happen to have a reference to a comparison with https://github.com/PyGithub/PyGithub which I suppose would be the most used alternative?

**Comment by bmunkholm** [comment]
I noticed e.g. [this API change](https://github.blog/changelog/2023-03-30-repository-security-advisories-rest-api/) which isn't supported yet by this lib? What drives your decision when to release? Wouldn't that we when new APIs are available?

**Comment by jph00** [comment]
Thanks for pointing that out @bmunkholm. At the moment I release any time a user points out an API change we're missing (or if I notice one). The lib is updated automatically from the OpenAPI spec by just running `examples/build.py`, but currently there isn't any automation to kick this off - I have to run it myself (or you can run it and submit a PR with the resulting changes).

pygithub uses a very different approach - they don't (AFAIK) have full coverage of the API, but instead provide a more pythonic interface over certain parts of it. ghapi instead is 100% compatible with the exact API documented by GitHub, and adds a CLI, mapping to python methods, docs, REPL autocomplete, etc. Personally I like to be able to just use the full API with all the conveniences of python, but I know some folks prefer the pygithub approach too. I guess try both and see what you like best and what works for you!

I've just done a new release so it should be all up to date now. If you see anything missing, please let me know in a new issue. (It's best to at-notify me if you want my prompt attention.)
