### ISSUE TITLE
v1.0.4

### ISSUE THREAD

**Issue by raeganbarker** [fastai/ghapi#162]
Dependabot recently recommended that I update to v1.0.4. I can see this release on [pypi](https://pypi.org/project/ghapi/1.0.4/), but I don't see anything about it on the ghapi GitHub: No release, release notes, tags, PRs, etc. Is this an actual approved release?

**Comment by per1234** [comment]
@jph00 a lack of release notes is understandable in this case, but please, please push a Git tag for each release.

**Comment by jph00** [comment]
Sure I can try to remember to do that -- just for my own info, how do you use git tags here? (i.e. how is this helpful to you?)

**Comment by rafrafek** [comment]
I think many people use tags to compare changes between versions, e.g. https://github.com/fastai/ghapi/compare/1.0.1...1.0.3
