### ISSUE TITLE
Provide static API documentation 

### ISSUE THREAD

**Issue by laurenty** [fastai/ghapi#166]
It would be nice if the site for `ghapi` provided browsable/searchable documentation. 
I understand that the documentation is supposed to be available using Jupyter Notebooks, but for users that aren't familiar with it this is just another obstacle. 
Also, the site mentions:
>To open any page as an interactive notebook in Google Colab, click the Colab badge at the top of the page.

I could not find a Colab badge anywhere...

Thanks!

**Comment by jph00** [comment]
Documentation is here https://ghapi.fast.ai/
