### ISSUE TITLE
Remove `pip` from dependencies

### ISSUE THREAD

**Issue by rafrafek** [fastai/ghapi#172]
Please remove `pip` from this line:

https://github.com/fastai/ghapi/blob/df2a68f081bb79ce9522cfcb7024c36d486ec336/setup.py#L29

I'm not sure if `packaging` can also be removed.

see https://github.com/fastai/fastcore/issues/540

**Comment by jph00** [comment]
Done.

**Comment by rafrafek** [comment]
Thanks!
