### ISSUE TITLE
Please add missing tags to the git repository for 1.x releases

### ISSUE THREAD

**Issue by gtkramer** [fastai/ghapi#176]
According to [the ghapi Python package release history on PyPI](https://pypi.org/project/ghapi/#history), there are releases for 1.0.2, 1.0.4, and 1.0.5, but corresponding tags do not exist on the GitHub repository.  Can these be retroactively added?  Or at least added with the next 1.0.6 release?

**Comment by rafrafek** [comment]
Can it be re-opened?

**Comment by gtkramer** [comment]
My team decided to use PyGithub instead of this project.  Feel free to file another new issue to open this again, but I won't be driving this one.
