### ISSUE TITLE
How does this library generates the client with OpenAPI?

### ISSUE THREAD

**Issue by noklam** [fastai/ghapi#179]
Thanks for creating the library. I think the idea of generating client with OpenAPI awesome and particularly like the interactiveness enabled by notebook. I'd like to re-use the mechanism on some other API.

I found https://ghapi.fast.ai/build_lib.html but there is not much describing what is happening behind the scene. Is there any blog post/docs that explains this with more details?

**Comment by jph00** [comment]
No sorry - just the source code for that module.
