### ISSUE TITLE
Support GHE

### ISSUE THREAD

**Issue by tomasaschan** [fastai/ghapi#29]
This looks awesome!

My team has lots of code that dumps data from an internal GHE instance, and I'd love to experiment with replacing much of that code with usage of this library instead. However, looking at [the source code](https://github.com/fastai/ghapi/blob/master/ghapi/core.py#L19-L20) it seems like this library is currently hard-coded to work only with github.com.

Are there any plans to extend this with support for GHE instances on custom URLs?

**Comment by hamelsmu** [comment]
We don't have a good way of testing the endpoints on GHE (should work in theory), however, we can give you a way to override GH_HOST.

**Comment by tomasaschan** [comment]
Nice, thanks for very quick turnaround!
