### ISSUE TITLE
user/ org population for `.search`?

### ISSUE THREAD

**Issue by ivirshup** [fastai/ghapi#35]
## Example

```python
print(
    GhApi(owner="theislab", repo="scanpy")
    .search
    .issues_and_pull_requests('label:"backport needed" type:pr')
    ["total_count"]
)
# 3678

print(
    GhApi(owner="theislab", repo="scanpy")
    .search
    .issues_and_pull_requests('repo:theislab/scanpy label:"backport needed" type:pr')
    ["total_count"]
)
# 20
```

## Description

I was confused by the behaviour of `GhApi(owner=..., repo=...).search.issues_and_pull_requests` until I realized it did not auto populate the `owner` and `repo` fields. This seems unintuitive to me. There are a few alternatives that I think would be a more clear:

* Populate these fields in search
* Don't make the search methods available if they aren't going to use the already provided fields.
* Add some mention of this to the docstring for `search`

**Comment by jph00** [comment]
The behavior and docs of the lib is just surfacing the behavior of the OpenAPI spec.
