### ISSUE TITLE
Unable to create gist using `GhApi().gists.create()`

### ISSUE THREAD

**Issue by lucharo** [fastai/ghapi#37]
Hello, 

I am trying to use `ghapi` to create gists. I am consistently getting `HTTP404NotFoundError: HTTP Error 404: Not Found` every time I try to create a gist using `GhApi().gists.create(...)`. I am authenticated and I can perform other operations such as fetching user data or fetching my own gists. This is the error I get and the code I am running:
![pic-selected-210207-2017-39](https://user-images.githubusercontent.com/47890755/107156947-30770d80-6979-11eb-8301-82735051a2cd.png)

This is the stack trace:
```python
---------------------------------------------------------------------------
HTTP404NotFoundError                      Traceback (most recent call last)
<ipython-input-155-f9c2313cdf94> in <module>
----> 1 ghapi.gists.create(description='ghapi test', files= 'CONTRIBUTING.md')

~/.config/miniconda3/envs/nb2medium/lib/python3.9/site-packages/ghapi/core.py in __call__(self, headers, *args, **kwargs)
     59         route_p,query_p,data_p = [{p:kwargs[p] for p in o if p in kwargs}
     60                                  for o in (self.route_ps,self.params,d)]
---> 61         return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
     62 
     63     def __str__(self): return f'{self.tag}.{self.name}{signature(self)}\n{self.doc_url}'

~/.config/miniconda3/envs/nb2medium/lib/python3.9/site-packages/ghapi/core.py in __call__(self, path, verb, headers, route, query, data)
    102         headers = {**self.headers,**(headers or {})}
    103         if path[:7] not in ('http://','https:/'): path = GH_HOST+path
--> 104         res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
    105                                      route=route or None, query=query or None, data=data or None)
    106         if 'X-RateLimit-Remaining' in self.recv_hdrs:

~/.config/miniconda3/envs/nb2medium/lib/python3.9/site-packages/fastcore/net.py in urlsend(url, verb, headers, route, query, data, json_data, return_json, return_headers, debug)
    173     req = urlrequest(url, verb, headers, route=route, query=query, data=data, json_data=json_data)
    174     if debug: debug(req)
--> 175     return urlread(req, return_json=return_json, return_headers=return_headers)
    176 
    177 # Cell

~/.config/miniconda3/envs/nb2medium/lib/python3.9/site-packages/fastcore/net.py in urlread(url, data, headers, decode, return_json, return_headers, **kwargs)
    110         with urlopen(url, data=data, headers=headers, **kwargs) as u: res,hdrs = u.read(),u.headers
    111     except HTTPError as e:
--> 112         if 400 <= e.code < 500: raise ExceptionsHTTP[e.code](e.url, e.hdrs, e.fp) from None
    113         else: raise
    114 

HTTP404NotFoundError: HTTP Error 404: Not Found

```

I am using python 3.9.1 and ghapi 0.1.16

**Comment by jph00** [comment]
This doesn't seem to be in the correct format for create gists - try doing a google search to find examples.

**Comment by derekmartinjs** [comment]
import json
import requests

GITHUB_API="https://api.github.com"
API_TOKEN='yourtoken'

#form a request URL
url=GITHUB_API+"/gists"
print("Request URL: %s"%url)

headers ={
    'Authorization': 'token %s' % API_TOKEN
}

params = {
 'scope': 'gist'   
}

payload = {
    "description": "An algorithm that describes obtaining the width and length of an underwater water cistern.",
    "public": True,
    "files": {
        "cistern.txt": {"content": "A cistern.\nThe height is 3.33, and a volume of 27.78 has been excavated.\nThe length exceeds the width by 0.83.\nYou should take the reciprocal of the height, 3.33, obtaining 0.3.\nMultiplay this by the volume, 27.78, obtaining 8.33.\nTake half of 0.83 and square it, obtaining 0.17.\nAdd 8.33 and you get 8.51.\nThe square root is 2.92.\nMake two copies of this, adding to the one 0.42 and subtracting from the other.\nYou find that 3.33 is the length and 2.5 is the width.\nThisis the procedure." 
    }
  }
}

res = requests.post(url, headers=headers, params=params, data=json.dumps(payload))

**Comment by jph00** [comment]
Here's how to do it in ghapi:

```python
from ghapi.core import GhApi
gists = GhApi().gists
gist = gists.create("testing gist", public=True, files={"test.txt": {"content": "My content"}})
print(gist.html_url)
gists.delete(gist.id)
```
