### ISSUE TITLE
Cancel an organization invitation - not supported?

### ISSUE THREAD

**Issue by rupaschomaker** [fastai/ghapi#43]
I can find a description in the yaml file:
https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml

but nothing in ghapi metadata.py, so it looks like a refresh is needed?

Docs: https://docs.github.com/en/rest/reference/orgs#cancel-an-organization-invitation

**Comment by jph00** [comment]
Seems to be there now: `api.orgs.cancel_invitation`
