### ISSUE TITLE
Consider using direct imports in the GitHub actions demo

### ISSUE THREAD

**Issue by choldgraf** [fastai/ghapi#45]
First of all, this tool is amazing, thanks 🚀

I am trying to figure out how to use `ghapi` inside of a GitHub Action. In reading through [this nice example](https://ghapi.fast.ai/tutorial_actions.html), I found it hard to track down where some functions were because of the `*` at the top.

As one example, I was looking for the `github_token` function referenced in the docs. The imports in there only list `from ghapi import *` whereas that function is actually at `ghapi.actions import github_token`, so I had to look at the github repository codebase to find it.

It would be helpful for newcomers if direct imports were used over the `*` syntax so they don't have to go hunting for the location of stuff! (at least, for stodgy old newcomers like me who don't like doing `import *` 😅)

**Comment by hamelsmu** [comment]
Hi @choldgraf this is a fairly opinionated corner of fastai styling, so I'll try my best to explain.  The current assumption is that people will use "live coding environments"  to quickly grab the location like this

![image](https://user-images.githubusercontent.com/1483922/116456090-aec7ab00-a816-11eb-8e69-5574c0f09160.png)

@jph00 am I explaining this correctly?

**Comment by jph00** [comment]
I would have thought pretty much all editors would show where imports come from - I don't think it requires jupyter.

**Comment by choldgraf** [comment]
In my case I was just trying to infer it directly from the docs. Eventually I was able to figure it out from using Vscode, but it just wasn't what I'm used to and took a bit of digging. Understand if you wanna stick with the * though, feel free to close
