### ISSUE TITLE
Moving a Project card results in HTTP422UnprocessableEntityError

### ISSUE THREAD

**Issue by choldgraf** [fastai/ghapi#52]
# What I'm trying to do

I'm trying to use this library to move a GitHub Project card to the top of its list. The context here is that some cards point to issues with a `🔥 priority` label, and I'd like to write a short script that:

- Loops through each card in a column
- If that card points to an issue (via `content_url`), grab the issue's list of labels
- If `priority` is in one of the labels, then bump the card to the top of the column.

# What's not working

Whenever I try to move a card using `ghapi`, e.g. via:

```python
api.projects.move_card(59656056, 0)
```

I get this message:

```
HTTP422UnprocessableEntityError: HTTP Error 422: Unprocessable Entity
```

If I debug and look at the URL of the `Request` object, it doesn't seem quite right

```
req.full_url
> 'https://api.github.com/projects/columns/cards/59656056/moves'
```

I'm not sure if I'm doing something wrong, or if this is a bug. So, opening it in case others have a suggestion :-)

**Comment by hamelsmu** [comment]
BTW - Please feel free to tag me in issues from now on for some reason this didn't get on my radar.  Looking into this now.

**Comment by hamelsmu** [comment]
Do you mind sharing the full code that created this error?

**Comment by choldgraf** [comment]
Sure - though it is just the one-liner.

Given a card, for example this one:

https://github.com/orgs/jupyterhub/projects/1#card-15417167

with a card ID of `15417167`

running this:

```
api.projects.move_card(15417167, 0)
```

results in `HTTP422UnprocessableEntityError: HTTP Error 422: Unprocessable Entity`

**Comment by choldgraf** [comment]
friendly ping for @hamelsmu in case he isn't watching this repo :-)

**Comment by choldgraf** [comment]
No worries - in case this is helpful, I'd basically like to make this function work :-)

```python
def sort_cards(column_id, labels, api):
    """Sort the cards in a GitHub Project column based on a list of labels.
    
    Note: cards that do not directly point to a GitHub issue will be treated
    like cards with issues that do not have one of the specified labels.
    
    Parameters
    ----------
    column_id: int
        The unique ID of the column you'd like to sort
    labels: list of strings
        A list of strings to use in sorting your cards. The cards will be sorted
        such that cards with first item of `labels` will come first.
    """
    if api is None:
        api = GhApi()
    cards = api.projects.list_cards(column['id'])
    for card in cards:
        # If the card points to an issue, grab its list of labels
        if "content_url" not in card:
            continue
        _, org, repo, _, num = card['content_url'].rsplit('/', 4)
        issue_labels = api.issues.list_labels_on_issue(org, repo, num)
        
        # Loop in reverse so that the first items in `labels` end up at the top
        for label in labels[::-1]:
            if any(label in ii['name'] for ii in issue_labels):
                api.projects.move_card(str(card['id']), 0)
                print(f"Moved card {card['id']}")
```

My use-case here is that I'd like to make it easier to "sort" the cards on a project board, based on the labels on issues they point to. The most obvious use for this is projects that have **priority labels** (so that `priority:high` would be at the top)

**Comment by hamelsmu** [comment]
That definitely helps thanks for providing this appreciate it

**Comment by choldgraf** [comment]
In case this helps debug: it also seems like this is the case for moving columns to other positions as well - so perhaps it has something to do with putting the right information in the **body** of the API call. E.g., the [`move_card` API](https://docs.github.com/en/rest/reference/projects#move-a-project-card) has this example:

```shell
curl \
  -X POST \
  -H "Accept: application/vnd.github.inertia-preview+json" \
  https://api.github.com/projects/columns/cards/42/moves \
  -d '{"position":"position"}'
```

And it sounds like the problem we're running into is in the generation of the `-d '{"position":"position"}'` part of the call.

**Comment by choldgraf** [comment]
Ah bummer, I will try to figure something out

**Comment by choldgraf** [comment]
ah I think I finally figured this out. The problem is that the `position` key _does not take a numerical argument_ (such as 0, 1, 2, etc). It takes a string like `top` or `bottom`. That's why it wasn't working.

This issue is resolved for me, and is really more of a GitHub Projects API documentation bug than here, so I'll close this
