### ISSUE TITLE
Is the build library generalizble to other APIs that follow the OpenAPI spec?

### ISSUE THREAD

**Issue by safeaim** [fastai/ghapi#67]
Hi,

Looking at the code in `https://github.com/fastai/ghapi/blob/master/ghapi/build_lib.py` it would seem that this code could be used for other APIs as well, that are not Github-related, is this correct? Or am I misunderstanding something here?

Regards,
Safet

**Comment by jph00** [comment]
Yes I'd expect so, although I only handle enough of OpenAPI to deal with what's actually used in the GH API. The stuff in core.py should also work for other OpenAPI projects.

If you try using these for other APIs, please let me know how it goes!
