### ISSUE TITLE
Finding pull requests linked to issues

### ISSUE THREAD

**Issue by wknapik** [fastai/ghapi#75]
Hi,

I can't figure out a way to find pull requests linked to an issue without iterating through all the PRs.

I thought I'd work around this by setting specific titles, or additional labels on PRs, but it seems there's no way to search PRs by title, or labels.

What's the best way to do this with ghapi? Do I really have to inspect each PR one by one? 

Thanks.

**Comment by jph00** [comment]
Sorry we can't provide support on using the GitHub API - I suggest you ask on Stackoverflow or similar
