### ISSUE TITLE
Async / await support

### ISSUE THREAD

**Issue by AlexandreODelisle** [fastai/ghapi#92]
Question, 

I haven't seen any support for native aiohttp calls . 

Is it something that could be implemented later in time? 

Thanks,

**Comment by dhirschfeld** [comment]
The lack of async (specifically `trio`) support has so far stopped me investigating `ghapi` further.

For managing rate limits `aiometer` could help:
https://github.com/florimondmanca/aiometer

**Comment by flying-sheep** [comment]
Why is this closed?

**Comment by jph00** [comment]
There's no plans to implement it - although if someone wants to try a PR and it turns out to be reasonably simple, I'd be open to looking at it.

**Comment by flying-sheep** [comment]
Thanks for clarifying!
